name: Tests
on: [push, pull_request]
jobs:
  run_tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        emacs_version: ["26.3", "27.2", "28.2"]
    steps:
      # This command allows us to execute cask below. Refer to issue:
      #  https://github.com/conao3/setup-cask/issues/6
      - run: echo "ACTIONS_ALLOW_UNSECURE_COMMANDS=true" >> $GITHUB_ENV
      - uses: purcell/setup-emacs@master
        with:
          version: ${{ matrix.emacs_version }}
      - uses: conao3/setup-cask@master
        with:
          version: '0.8.4'
      - uses: actions/checkout@v3
      - run: |
          cask install
          make test
